#!/bin/bash

if [[ -z $1  || -z $2 || -z $3 ]]; then
	echo "Usage: $0 <project> <year> <month>" 2>&1
	exit 1
fi

if [ -z "$CLIENT_ID" ]; then
	echo "error: CLIENT_ID undefined"
	exit 1
fi
if [ -z "$CLIENT_SECRET" ]; then
	echo "error: CLIENT_SECRET undefined"
	exit 1
fi


EXAM=false
if [ $1 = "rush-00" ]; then
	ID="1308"
elif [ $1 == "rush-01" ]; then
	ID="1310"
elif [ $1 == "rush-02" ]; then
	ID="1309"
elif [ $1 == "bsq" ]; then
	ID="1305"
elif [ $1 == "exam-00" ]; then
	ID="1301"
	EXAM=true
elif [ $1 == "exam-01" ]; then
	ID="1302"
	EXAM=true
elif [ $1 == "exam-02" ]; then
	ID="1303"
	EXAM=true
elif [ $1 == "exam-03" ]; then
	ID="1304"
	EXAM=true
elif [ $1 == "shell-00" ]; then
	ID="1255"
elif [ $1 == "shell-01" ]; then
	ID="1256"
elif [ $1 == "c-00" ]; then
	ID="1257"
elif [ $1 == "c-01" ]; then
	ID="1258"
elif [ $1 == "c-02" ]; then
	ID="1259"
elif [ $1 == "c-03" ]; then
	ID="1260"
elif [ $1 == "c-04" ]; then
	ID="1261"
elif [ $1 == "c-05" ]; then
	ID="1262"
elif [ $1 == "c-06" ]; then
	ID="1263"
elif [ $1 == "c-07" ]; then
	ID="1270"
elif [ $1 == "c-08" ]; then
	ID="1264"
elif [ $1 == "c-09" ]; then
	ID="1265"
elif [ $1 == "c-10" ]; then
	ID="1266"
elif [ $1 == "c-11" ]; then
	ID="1267"
elif [ $1 == "c-12" ]; then
	ID="1268"
elif [ $1 == "c-13" ]; then
	ID="1271"
fi

MONTH=
LAST_DAY=
if [ $3 = "january" ]; then
	MONTH="01"
	LAST_DAY="31"
elif [ $3 = "february" ]; then
	MONTH="02"
	if (( ( $1 % 4 == 0 && $1 % 100 != 0 ) || $1 % 400 == 0 )); then
		LAST_DAY="29"
	else
		LAST_DAY="28"
	fi
elif [ $3 = "march" ]; then
	MONTH="03"
	LAST_DAY="31"
elif [ $3 = "april" ]; then
	MONTH="04"
	LAST_DAY="30"
elif [ $3 = "may" ]; then
	MONTH="05"
	LAST_DAY="31"
elif [ $3 = "june" ]; then
	MONTH="06"
	LAST_DAY="30"
elif [ $3 = "july" ]; then
	MONTH="07"
	LAST_DAY="31"
elif [ $3 = "august" ]; then
	MONTH="08"
	LAST_DAY="31"
elif [ $3 = "september" ]; then
	MONTH="09"
	LAST_DAY="30"
elif [ $3 = "october" ]; then
	MONTH="10"
	LAST_DAY="31"
elif [ $3 = "november" ]; then
	MONTH="11"
	LAST_DAY="30"
elif [ $3 = "december" ]; then
	MONTH="12"
	LAST_DAY="31"
else
	echo "Month is not valid !" 2>&1
	exit 1
fi

DATE_1="$2-$MONTH-01T01:00:00.205Z"
DATE_2="$2-$MONTH-""$LAST_DAY""T23:00:00.205Z"
ACCESS_TOKEN=$(curl -s -X POST --data "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET" https://api.intra.42.fr/oauth/token | jq -r '.access_token')

DATA_1=$(curl -s -G -H "Authorization: Bearer $ACCESS_TOKEN" \
	--data-urlencode "page[size]=100" \
	--data-urlencode "filter[campus]=62" \
	--data-urlencode "range[marked_at]=$DATE_1,$DATE_2" \
	"https://api.intra.42.fr/v2/projects/$ID/projects_users")

DATA_2=$(curl -s -G -H "Authorization: Bearer $ACCESS_TOKEN" \
	--data-urlencode "page[size]=100" \
	--data-urlencode "page[number]=2" \
	--data-urlencode "filter[campus]=62" \
	--data-urlencode "range[marked_at]=$DATE_1,$DATE_2" \
	"https://api.intra.42.fr/v2/projects/$ID/projects_users")

DATA=$(echo "$DATA_1 $DATA_2" | jq -s '.[0] + .[1]' | jq 'sort_by([-.final_mark, .marked_at])')
if [ "$DATA" = "[]" ]; then
	echo "Project not found."
	exit
fi

PROCESS=$(echo "$DATA" | jq -r '.[] | "&\(.user.login)&\(.final_mark)&\(.status)"' | cat -n)
GREEN='\033[0;32m'
RES='\033[0m'
echo -e "\t=== 🦖 DINO TRACKER 🦕 ===\n"
while IFS='&' read -r index login level status; do
	index=$(echo "$index" | awk '{$1=$1;print}')
	if [ "$index" = "1" ]; then
		index="👑"
	elif [ "$index" = "2" ]; then
		index="🥈"
	elif [ "$index" = "3" ]; then
		index="🥉"
	fi

	if [[ $status = "finished" && $EXAM = true ]]; then
		echo -en $GREEN
	fi

	url_login=$(printf "\e]8;;https://profile.intra.42.fr/users/$login\e\\%-8s\e]8;;\e\\" "$login")
	printf "\t%-4s\t%s\t%d\n"	"$index" \
					"$url_login" \
					"$level"
	echo -en $RES
	if [ "$index" = "🥉" ]; then
		echo
	fi
	sleep 0.01
done <<< "$PROCESS"
